name: Build and Deploy to Github Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
      - run: deno task ok
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Built static/
          commit_user_name: BlackAsLight
          commit_user_email: 44320105+BlackAsLight@users.noreply.github.com
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v1
        with:
          path: 'static/'
      - id: deployment
        uses: actions/deploy-pages@v2
